import type { Metadata } from 'next'
import StoryblokProvider from '@/components/StoryblokProvider'

import './globals.css'

export const revalidate = 0
export const fetchCache = 'force-no-store'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<StoryblokProvider>
			<html lang="en">
				<body className="">{children}</body>
			</html>
		</StoryblokProvider>
	)
}
