import type { Metadata } from 'next'
import { StoryblokProvider } from '@/provider'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'

import './globals.css'

export const revalidate = 0
export const fetchCache = 'force-no-store'

export const metadata: Metadata = {
	title: 'Storyblok - Next15 - Tailwindcss',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<StoryblokProvider>
			<html lang="en">
				<body className="m-10">{children}</body>
			</html>
		</StoryblokProvider>
	)
}
